// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type YoutubeSearchResult = {
  id: string;
  title: string;
  channel: string;
  duration_secs: number;
};
